name: YouTube 4K VP9 Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک ویدیو یوتیوب'
        required: true
        default: 'https://www.youtube.com/watch?v=F7sGJVUrkjQ'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup yt-dlp with Cookies
        uses: AnimMouse/setup-yt-dlp@v3
        with:
          yt-dlp-version: latest

      - name: Setup YouTube Cookies
        uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Download 4K VP9 + Best Audio
        run: |
          yt-dlp -v \
            -f "313+251/313+bestaudio/bestvideo[height=2160][vcodec^=vp09]+bestaudio[acodec^=opus]/bestvideo[height<=2160]+bestaudio" \
            --merge-output-format webm \
            --extractor-args "youtube:player_client=web_safari,web,ios,android,web_creator,web_embedded,web_music" \
            --no-warnings \
            "${{ github.event.inputs.url }}"
