name: YouTube 4K Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک ویدیو'
        required: true
        default: 'https://www.youtube.com/watch?v=F7sGJVUrkjQ'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp
        run: pip install -U yt-dlp

      - name: Put Cookies
        run: |
          cat > cookies.txt << 'EOF'
          ${{ secrets.YOUTUBE_COOKIES }}
          EOF

      - name: Download 4K VP9
        run: |
          yt-dlp -v \
            -f "313+251/313+bestaudio/bestvideo[height=2160][vcodec^=vp09]+bestaudio/bestvideo[height<=2160]+bestaudio" \
            --merge-output-format webm \
            --cookies cookies.txt \
            --extractor-args "youtube:player_client=web_safari,web,ios,android,web_creator" \
            "${{ github.event.inputs.url }}"
