name: YouTube 4K VP9 Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'لینک ویدیو یوتیوب'
        required: true
        default: 'https://www.youtube.com/watch?v=F7sGJVUrkjQ'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp + ffmpeg + Deno
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install -U yt-dlp
          curl -fsSL https://deno.land/install.sh | sh -s -- --yes
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Save Cookies
        run: |
          cat > cookies.txt << 'EOF'
          ${{ secrets.YOUTUBE_COOKIES }}
          EOF

      - name: Download 4K VP9
        run: |
          yt-dlp -v \
            --cookies cookies.txt \
            -f "313+251/313+bestaudio/bestvideo[height=2160][vcodec^=vp09]+bestaudio[acodec^=opus]/bestvideo[height<=2160]+bestaudio/best" \
            --merge-output-format webm \
            --extractor-args "youtube:player_client=web_safari,web,ios,android,web_creator,web_embedded,web_music" \
            --js-runtimes deno \
            --no-warnings \
            "${{ github.event.inputs.url }}"
